@RecipeSuggester.Api_HostAddress = https://localhost:44318

GET {{RecipeSuggester.Api_HostAddress}}/test

###

@prompt=Who built the ollama AI model
POST {{RecipeSuggester.Api_HostAddress}}/recipes?prompt={{prompt}}

###
