namespace RecipeSuggester.Api.Features.SuggestRecipe;

/// <summary>
/// Gets or sets the suggested recipe response generated by the system.
/// </summary>
public class SuggestRecipeResponse
{
    public required string RecipeResponse { get; set; }
}
